name: Deploy to Multiple environments

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Comma separated list of environments to deploy to'
        type: string
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set-matrix.outputs.environments }}
    steps:
      - id: set-matrix
        run: |
          echo "environments=[$(echo ${{ inputs.environments }} | sed 's/,/","/g' | sed 's/^/"/;s/$/"/')]"
          echo "environments=[$(echo ${{ inputs.environments }} | sed 's/,/","/g' | sed 's/^/"/;s/$/"/')]" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.environments) }}
    with:
      environment: ${{ matrix.environment }}